# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=40)),
                ('doc_number', models.CharField(max_length=20)),
                ('doc_date', models.DateTimeField()),
                ('apl_name', models.CharField(max_length=250)),
                ('apl_inn', models.CharField(max_length=50)),
                ('apl_kpp', models.CharField(max_length=9)),
                ('apl_address', models.CharField(max_length=250)),
                ('stock', models.CharField(max_length=50)),
                ('account', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=3)),
                ('total_sum', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DocTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=250)),
                ('unit_id', models.CharField(max_length=10)),
                ('unit_code', models.CharField(max_length=3)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docdata.DocHeader')),
            ],
        ),
    ]
