# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docheader',
            name='pp_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='docheader',
            name='sf_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
