# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdata', '0005_auto_20160123_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctable',
            name='country_code',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='doctable',
            name='gtd',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='doctable',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctable',
            name='item_sum',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='doctable',
            name='qty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='doctable',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
