# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdata', '0006_auto_20160123_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctable',
            name='country_code',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='doctable',
            name='gtd',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='doctable',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doctable',
            name='item_sum',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='doctable',
            name='width',
            field=models.IntegerField(),
        ),
    ]
