# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdata', '0007_auto_20160123_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docheader',
            name='pp_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='docheader',
            name='sf_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
