# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdata', '0008_auto_20160123_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docheader',
            name='account',
            field=models.CharField(max_length=20, verbose_name='Р/счет'),
        ),
        migrations.AlterField(
            model_name='docheader',
            name='apl_address',
            field=models.CharField(max_length=250, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='docheader',
            name='apl_inn',
            field=models.CharField(max_length=50, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='docheader',
            name='apl_kpp',
            field=models.CharField(max_length=9, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='docheader',
            name='apl_name',
            field=models.CharField(max_length=250, verbose_name='Контрагент'),
        ),
        migrations.AlterField(
            model_name='docheader',
            name='currency',
            field=models.CharField(max_length=3, verbose_name='Вал'),
        ),
        migrations.AlterField(
            model_name='docheader',
            name='doc_date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='docheader',
            name='doc_number',
            field=models.CharField(max_length=20, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='docheader',
            name='doc_type',
            field=models.CharField(max_length=40, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='docheader',
            name='pp_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='№ п\\п'),
        ),
        migrations.AlterField(
            model_name='docheader',
            name='sf_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='№ с-ф'),
        ),
        migrations.AlterField(
            model_name='docheader',
            name='stock',
            field=models.CharField(max_length=50, verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='docheader',
            name='total_sum',
            field=models.FloatField(verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='doctable',
            name='qty',
            field=models.FloatField(default=1),
        ),
    ]
