# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docdata', '0009_auto_20160123_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apl_id', models.CharField(max_length=20, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Контрагент')),
                ('inn', models.CharField(max_length=50, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=9, verbose_name='КПП')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(max_length=20, verbose_name='Артикул')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('unit_id', models.CharField(max_length=10, verbose_name='ед.')),
                ('unit_code', models.CharField(max_length=3, verbose_name='Код')),
            ],
        ),
        migrations.AlterField(
            model_name='doctable',
            name='art',
            field=models.CharField(max_length=20, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='doctable',
            name='country_code',
            field=models.CharField(max_length=2, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='doctable',
            name='gtd',
            field=models.CharField(max_length=30, verbose_name='ГТД'),
        ),
        migrations.AlterField(
            model_name='doctable',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docdata.DocHeader', verbose_name='№ документа'),
        ),
        migrations.AlterField(
            model_name='doctable',
            name='height',
            field=models.IntegerField(verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='doctable',
            name='item_sum',
            field=models.FloatField(verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='doctable',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='doctable',
            name='qty',
            field=models.FloatField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='doctable',
            name='unit_code',
            field=models.CharField(max_length=3, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='doctable',
            name='unit_id',
            field=models.CharField(max_length=10, verbose_name='ед.'),
        ),
        migrations.AlterField(
            model_name='doctable',
            name='width',
            field=models.IntegerField(verbose_name='Ширина'),
        ),
    ]
