# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdata', '0012_auto_20160131_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='need_to_import',
            field=models.BooleanField(default=False, verbose_name='Нужен импорт'),
        ),
        migrations.AddField(
            model_name='product',
            name='full_name',
            field=models.CharField(default='', max_length=250, verbose_name='Описание'),
        ),
    ]
