# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdata', '0013_auto_20160131_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='full_name',
            field=models.CharField(default='', max_length=1024, verbose_name='Описание'),
        ),
    ]
