# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='hld',
            field=models.CharField(default=b'', max_length=20, verbose_name='\u0425\u043e\u043b\u0434\u0438\u043d\u0433'),
        ),
    ]
