# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdata', '0002_contractor_hld'),
    ]

    operations = [
        migrations.AddField(
            model_name='docheader',
            name='rate',
            field=models.FloatField(default=1.0, verbose_name='Курс валюты'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='hld',
            field=models.CharField(default='', max_length=20, verbose_name='Холдинг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_name',
            field=models.CharField(default='', max_length=1024, verbose_name='Описание'),
        ),
    ]
