# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdata', '0003_auto_20160219_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctable',
            name='item_weight',
            field=models.FloatField(default=1.0, verbose_name='Вес в кг'),
        ),
        migrations.AddField(
            model_name='product',
            name='net_weight',
            field=models.FloatField(default=1.0, verbose_name='Вес в кг'),
        ),
    ]
