# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdata', '0004_auto_20160219_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='hld',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Холдинг'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='kpp',
            field=models.CharField(blank=True, max_length=9, verbose_name='КПП'),
        ),
    ]
