# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docdata', '0005_auto_20160405_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsQty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(max_length=20, verbose_name='Артикул')),
                ('stock_id', models.CharField(max_length=20, verbose_name='Склад')),
                ('gtd', models.CharField(max_length=30, verbose_name='ГТД')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('qty', models.FloatField(default=1, verbose_name='Количество')),
            ],
        ),
    ]
